import fs from 'fs';

const GAS_URL = 'https://script.google.com/macros/s/AKfycbxS1_Vp3Xs33FBXxWFaOXNCsOBNrrOU21OtyF44POb8ILMujJ4_04XB-zGxA0rsb7Fv/exec';
const BUTCHERY_CATEGORIES = ["لحوم كندوز", "لحوم ضاني", "مصنعات", "حلويات العجل"];

async function run() {
  console.log("Fetching live menu from Google Sheets...");
  try {
    const res = await fetch(`${GAS_URL}?action=get_menu`);
    const data = await res.json();

    if (data.success && data.menu) {
      const groups = {};
      data.menu.forEach(item => {
        if (!groups[item.category]) groups[item.category] = [];
        groups[item.category].push(item);
      });

      const hawawshiMenu = [];
      const butcheryMenu = [];

      Object.keys(groups).forEach(cat => {
        const section = { category: cat, items: groups[cat] };
        if (BUTCHERY_CATEGORIES.includes(cat) || cat.includes('جزارة') || cat.includes('لحوم')) {
          butcheryMenu.push(section);
        } else {
          hawawshiMenu.push(section);
        }
      });

      const fileContent = `
// ── AUTOGENERATED BY PREBUILD SCRIPT ──
export const hawawshiMenu = ${JSON.stringify(hawawshiMenu, null, 2)};
export const butcheryMenu = ${JSON.stringify(butcheryMenu, null, 2)};
`;

      fs.writeFileSync('./src/data.js', fileContent, 'utf8');
      console.log("Menu successfully built and injected into src/data.js!");
    } else {
      console.error("Failed to fetch menu or menu is empty.");
      process.exit(1);
    }
  } catch (e) {
    console.error("Error during prebuild:", e);
    process.exit(1);
  }
}

run();
