
// ── AUTOGENERATED BY PREBUILD SCRIPT ──
export const hawawshiMenu = [
  {
    "category": "الحواوشي",
    "items": [
      {
        "category": "الحواوشي",
        "name": "حواوشي سادة",
        "desc": "",
        "price": 105
      },
      {
        "category": "الحواوشي",
        "name": "حواوشي بالسجق",
        "desc": "",
        "price": 135
      },
      {
        "category": "الحواوشي",
        "name": "حواوشي بسطرمة",
        "desc": "",
        "price": 130
      },
      {
        "category": "الحواوشي",
        "name": "حواوشي أستيك",
        "desc": "حواوشي اللحم مع اضافة شريحتين استيك جريل",
        "price": 240
      },
      {
        "category": "الحواوشي",
        "name": "حواوشي كبدة",
        "desc": "حواوشي سادة ويضاف عليه شرائح الكبدة",
        "price": 230
      },
      {
        "category": "الحواوشي",
        "name": "حواوشي سادة بالجبنة",
        "desc": "",
        "price": 130
      },
      {
        "category": "الحواوشي",
        "name": "حواوشي بالسجق والجبنة",
        "desc": "",
        "price": 155
      },
      {
        "category": "الحواوشي",
        "name": "حواوشي جبنة بسطرمة",
        "desc": "",
        "price": 155
      },
      {
        "category": "الحواوشي",
        "name": "حواوشي استيك بالجبنة",
        "desc": "الحواوشي اللحم مع اضافة شريحتين استيك مع مشكل من الجبن",
        "price": 265
      }
    ]
  },
  {
    "category": "المشويات",
    "items": [
      {
        "category": "المشويات",
        "name": "ميكس السعادة",
        "desc": "قطعة (كفتة - طرب - استيك - نيفة) ، تقدم مع الارز البسمتي",
        "price": 320
      },
      {
        "category": "المشويات",
        "name": "وجبة الباشا - صدر",
        "desc": "١/٨ كفتة مع ربع فرخة والارز البسمتي",
        "price": 220
      },
      {
        "category": "المشويات",
        "name": "وجبة الباشا - ورك",
        "desc": "١/٨ كفتة + ١/٤ فرخة مع الارز البسمتي",
        "price": 195
      },
      {
        "category": "المشويات",
        "name": "ربع كباب",
        "desc": "",
        "price": 360
      },
      {
        "category": "المشويات",
        "name": "ربع كفتة",
        "desc": "",
        "price": 240
      },
      {
        "category": "المشويات",
        "name": "ربع سجق",
        "desc": "",
        "price": 240
      },
      {
        "category": "المشويات",
        "name": "نصف فرخه",
        "desc": "",
        "price": 220
      },
      {
        "category": "المشويات",
        "name": "ربع نيفة",
        "desc": "",
        "price": 340
      },
      {
        "category": "المشويات",
        "name": "ربع ريش ضاني",
        "desc": "",
        "price": 360
      },
      {
        "category": "المشويات",
        "name": "ربع طرب",
        "desc": "",
        "price": 260
      },
      {
        "category": "المشويات",
        "name": "ربع مشكل كباب وكفتة",
        "desc": "",
        "price": 310
      },
      {
        "category": "المشويات",
        "name": "ربع استيك",
        "desc": "",
        "price": 280
      },
      {
        "category": "المشويات",
        "name": "موزة عضم مشوية",
        "desc": "مع أرز وبطاطس",
        "price": 500
      },
      {
        "category": "المشويات",
        "name": "ضلوع مشوية",
        "desc": "",
        "price": 310
      }
    ]
  },
  {
    "category": "الجريل",
    "items": [
      {
        "category": "الجريل",
        "name": "ربع لحمة",
        "desc": "ورقة لحمة",
        "price": 270
      },
      {
        "category": "الجريل",
        "name": "ربع سجق",
        "desc": "ورقة سجق",
        "price": 230
      },
      {
        "category": "الجريل",
        "name": "ربع مشكل",
        "desc": "كبد سجق او لحمة سجق",
        "price": 270
      },
      {
        "category": "الجريل",
        "name": "ربع كبدة",
        "desc": "ورقة كبدة",
        "price": 270
      },
      {
        "category": "الجريل",
        "name": "ربع استيك",
        "desc": "",
        "price": 290
      },
      {
        "category": "الجريل",
        "name": "تلت مشكل",
        "desc": "كبدة لحمة سجق",
        "price": 405
      }
    ]
  },
  {
    "category": "صواني الربيع",
    "items": [
      {
        "category": "صواني الربيع",
        "name": "صنية الربيع - NEW",
        "desc": "١/٤ فرخة + ١/٨ طرب + ١/٨ كفتة + ١/٨ كباب + رغيف حواوشي + أرز بسمتي + قطعتين سمبوسك جبنة",
        "price": 600
      },
      {
        "category": "صواني الربيع",
        "name": "صنية ضلوع ضاني",
        "desc": "",
        "price": 250
      }
    ]
  },
  {
    "category": "اطباق الربيع",
    "items": [
      {
        "category": "اطباق الربيع",
        "name": "فرد حمام ارز",
        "desc": "الحشو (فريك - أرز) وتقدم مع البطاطس",
        "price": 200
      },
      {
        "category": "اطباق الربيع",
        "name": "فرد حمام فريك",
        "desc": "",
        "price": 220
      },
      {
        "category": "اطباق الربيع",
        "name": "موزه مخلية",
        "desc": "تقدم مع الأرز",
        "price": 380
      },
      {
        "category": "اطباق الربيع",
        "name": "رقاق باللحمة",
        "desc": "",
        "price": 180
      },
      {
        "category": "اطباق الربيع",
        "name": "صنية كوارع بالحمص والنخاع",
        "desc": "",
        "price": 340
      },
      {
        "category": "اطباق الربيع",
        "name": "وجبة المعلم",
        "desc": "قطع اللحمة المحمرة في السمن البلدي ، تقدم مع البطاطس والأرز",
        "price": 300
      }
    ]
  },
  {
    "category": "الطواجن",
    "items": [
      {
        "category": "الطواجن",
        "name": "طاجن باور الربيع NEW",
        "desc": "عكاوي - كوارع - شرائح لحم - نخاع (بالبصل)",
        "price": 410
      },
      {
        "category": "الطواجن",
        "name": "طاجن عكاوي بالبصل",
        "desc": "",
        "price": 410
      },
      {
        "category": "الطواجن",
        "name": "طاجن لحم بالبامية",
        "desc": "",
        "price": 270
      },
      {
        "category": "الطواجن",
        "name": "طاجن لحمة بالفريك",
        "desc": "",
        "price": 270
      },
      {
        "category": "الطواجن",
        "name": "ملوخية",
        "desc": "",
        "price": 70
      },
      {
        "category": "الطواجن",
        "name": "ديناميت",
        "desc": "لحمة + سجق + ورق عنب",
        "price": 340
      },
      {
        "category": "الطواجن",
        "name": "طاجن لحم بالبصل",
        "desc": "",
        "price": 270
      },
      {
        "category": "الطواجن",
        "name": "طاجن لحمة بالبطاطس",
        "desc": "",
        "price": 270
      },
      {
        "category": "الطواجن",
        "name": "شوربة كوارع مخلية",
        "desc": "",
        "price": 290
      },
      {
        "category": "الطواجن",
        "name": "طاجن كوارع بورق العنب",
        "desc": "",
        "price": 380
      }
    ]
  },
  {
    "category": "طاسات الزبدة",
    "items": [
      {
        "category": "طاسات الزبدة",
        "name": "ربع لحمة",
        "desc": "",
        "price": 290
      },
      {
        "category": "طاسات الزبدة",
        "name": "ربع سجق",
        "desc": "",
        "price": 250
      },
      {
        "category": "طاسات الزبدة",
        "name": "ربع مشكل بالزبدة",
        "desc": "",
        "price": 290
      },
      {
        "category": "طاسات الزبدة",
        "name": "طلب مخ بالزبدة",
        "desc": "",
        "price": 280
      },
      {
        "category": "طاسات الزبدة",
        "name": "طلب مخ طاسة",
        "desc": "",
        "price": 280
      }
    ]
  },
  {
    "category": "طاسات المحمر باللية",
    "items": [
      {
        "category": "طاسات المحمر باللية",
        "name": "ربع كفتة",
        "desc": "",
        "price": 210
      },
      {
        "category": "طاسات المحمر باللية",
        "name": "ربع كبدة",
        "desc": "",
        "price": 290
      },
      {
        "category": "طاسات المحمر باللية",
        "name": "ربع مشكل",
        "desc": "",
        "price": 280
      },
      {
        "category": "طاسات المحمر باللية",
        "name": "طلب كبدة ردة بلدي",
        "desc": "",
        "price": 290
      },
      {
        "category": "طاسات المحمر باللية",
        "name": "طلب مشكل كبدة ردة ومخ",
        "desc": "",
        "price": 300
      }
    ]
  },
  {
    "category": "المكرونات",
    "items": [
      {
        "category": "المكرونات",
        "name": "مكرونة لحمة مفرومة",
        "desc": "",
        "price": 80
      },
      {
        "category": "المكرونات",
        "name": "مكرونة باللحم الجريل",
        "desc": "",
        "price": 230
      },
      {
        "category": "المكرونات",
        "name": "مكرونة بشاميل",
        "desc": "",
        "price": 200
      },
      {
        "category": "المكرونات",
        "name": "مكرونة بالسجق",
        "desc": "",
        "price": 210
      },
      {
        "category": "المكرونات",
        "name": "مكرونة بالكبدة",
        "desc": "",
        "price": 230
      },
      {
        "category": "المكرونات",
        "name": "مكرونة كفتة",
        "desc": "",
        "price": 200
      }
    ]
  },
  {
    "category": "الفتة",
    "items": [
      {
        "category": "الفتة",
        "name": "فتة سادة",
        "desc": "",
        "price": 80
      },
      {
        "category": "الفتة",
        "name": "فتة بالكبدة",
        "desc": "",
        "price": 240
      },
      {
        "category": "الفتة",
        "name": "فتة بالكوارع",
        "desc": "",
        "price": 330
      },
      {
        "category": "الفتة",
        "name": "فتة باللحمة الجريل",
        "desc": "",
        "price": 240
      },
      {
        "category": "الفتة",
        "name": "فتة بالسجق",
        "desc": "",
        "price": 220
      },
      {
        "category": "الفتة",
        "name": "فتة العمدة",
        "desc": "قطع اللحمة المحمرة بالسمن البلدي و طشة الربيع المميزة",
        "price": 300
      }
    ]
  },
  {
    "category": "طواجن الارز",
    "items": [
      {
        "category": "طواجن الارز",
        "name": "ارز بالشعرية",
        "desc": "",
        "price": 70
      },
      {
        "category": "طواجن الارز",
        "name": "ارز بالكبدة",
        "desc": "",
        "price": 230
      },
      {
        "category": "طواجن الارز",
        "name": "ارز بالطشة",
        "desc": "",
        "price": 80
      },
      {
        "category": "طواجن الارز",
        "name": "ارز بالسجق",
        "desc": "",
        "price": 210
      },
      {
        "category": "طواجن الارز",
        "name": "ارز باللحمة",
        "desc": "",
        "price": 230
      }
    ]
  },
  {
    "category": "قسم المقبلات",
    "items": [
      {
        "category": "قسم المقبلات",
        "name": "طلب ممبار",
        "desc": "",
        "price": 150
      },
      {
        "category": "قسم المقبلات",
        "name": "محشي مشكل",
        "desc": "باذنجان - كوسه - فلفل",
        "price": 110
      },
      {
        "category": "قسم المقبلات",
        "name": "ورق عنب سادة",
        "desc": "",
        "price": 100
      },
      {
        "category": "قسم المقبلات",
        "name": "شوربة سادة",
        "desc": "",
        "price": 30
      },
      {
        "category": "قسم المقبلات",
        "name": "سلطه مشكله",
        "desc": "باذنجان - جبنة - جرير",
        "price": 20
      },
      {
        "category": "قسم المقبلات",
        "name": "باذنجان",
        "desc": "",
        "price": 20
      },
      {
        "category": "قسم المقبلات",
        "name": "مسقعة",
        "desc": "",
        "price": 15
      },
      {
        "category": "قسم المقبلات",
        "name": "فرد سفرة",
        "desc": "السلطات الاساسية تقدم لفرد السفرة وتضاف إلي الفاتورة تلقائيا",
        "price": 25
      },
      {
        "category": "قسم المقبلات",
        "name": "شوربة لسان عصفور",
        "desc": "",
        "price": 40
      },
      {
        "category": "قسم المقبلات",
        "name": "باكت بطاطس",
        "desc": "",
        "price": 60
      },
      {
        "category": "قسم المقبلات",
        "name": "بابا غنوج",
        "desc": "",
        "price": 25
      },
      {
        "category": "قسم المقبلات",
        "name": "طماطم مخلله",
        "desc": "",
        "price": 25
      },
      {
        "category": "قسم المقبلات",
        "name": "سلطة كبدة بلسان العصفور",
        "desc": "",
        "price": 30
      }
    ]
  },
  {
    "category": "قسم العصائر",
    "items": [
      {
        "category": "قسم العصائر",
        "name": "ليمون نعناع",
        "desc": "منعش ومرطب: يروي العطش. غني بفيتامين سي: يعزز المناعة...",
        "price": 60
      },
      {
        "category": "قسم العصائر",
        "name": "فراولة",
        "desc": "",
        "price": 75
      },
      {
        "category": "قسم العصائر",
        "name": "مانجو",
        "desc": "يفضل محتواه العالي من فيتامين C وفيتامين A...",
        "price": 95
      },
      {
        "category": "قسم العصائر",
        "name": "سفن",
        "desc": "",
        "price": 25
      },
      {
        "category": "قسم العصائر",
        "name": "V cola",
        "desc": "",
        "price": 30
      },
      {
        "category": "قسم العصائر",
        "name": "بيبسي",
        "desc": "",
        "price": 25
      },
      {
        "category": "قسم العصائر",
        "name": "مياة صغيرة",
        "desc": "",
        "price": 10
      }
    ]
  }
];
export const butcheryMenu = [
  {
    "category": "لحوم كندوز",
    "items": [
      {
        "category": "لحوم كندوز",
        "name": "سن كندوز",
        "desc": "",
        "price": 500
      },
      {
        "category": "لحوم كندوز",
        "name": "رقبة كندوز",
        "desc": "",
        "price": 500
      },
      {
        "category": "لحوم كندوز",
        "name": "موزة كندوز",
        "desc": "",
        "price": 500
      },
      {
        "category": "لحوم كندوز",
        "name": "موزة كندوز صافي",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "قشرة لوحة كندوز",
        "desc": "",
        "price": 510
      },
      {
        "category": "لحوم كندوز",
        "name": "انتركوت كندوز",
        "desc": "",
        "price": 525
      },
      {
        "category": "لحوم كندوز",
        "name": "اوسو بكو",
        "desc": "",
        "price": 510
      },
      {
        "category": "لحوم كندوز",
        "name": "تيم هوك",
        "desc": "",
        "price": 510
      },
      {
        "category": "لحوم كندوز",
        "name": "ريب اى كندوز",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "تيبون ستيك كندوز",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "رستو كندوز",
        "desc": "",
        "price": 525
      },
      {
        "category": "لحوم كندوز",
        "name": "رستو كندوز صافي",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "كباب حلة كندوز عادى",
        "desc": "",
        "price": 525
      },
      {
        "category": "لحوم كندوز",
        "name": "كباب حلة كندوز صافى",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "وش فخدة",
        "desc": "",
        "price": 525
      },
      {
        "category": "لحوم كندوز",
        "name": "وش فخدة صافى",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "فلتو كندوز",
        "desc": "",
        "price": 575
      },
      {
        "category": "لحوم كندوز",
        "name": "شاورما كندوز احمر",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "بيكاتا كندوز صافى",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "ستيك كندوز صافي",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "بفتيك كندوز صافى",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "مفروم كندوز ملبس",
        "desc": "",
        "price": 430
      },
      {
        "category": "لحوم كندوز",
        "name": "مفروم كندوز عادى",
        "desc": "",
        "price": 500
      },
      {
        "category": "لحوم كندوز",
        "name": "مفروم كندوز صافى",
        "desc": "",
        "price": 550
      },
      {
        "category": "لحوم كندوز",
        "name": "دوش ملبس",
        "desc": "",
        "price": 430
      },
      {
        "category": "لحوم كندوز",
        "name": "شورت ريس",
        "desc": "",
        "price": 475
      },
      {
        "category": "لحوم كندوز",
        "name": "كبده كندوز مشكل",
        "desc": "",
        "price": 525
      },
      {
        "category": "لحوم كندوز",
        "name": "كبده كندوز صافى",
        "desc": "",
        "price": 575
      },
      {
        "category": "لحوم كندوز",
        "name": "موزة - خضار - مفروم",
        "desc": "فريش يوميًا",
        "price": 490
      },
      {
        "category": "لحوم كندوز",
        "name": "استيك - بفتيك - فلتو",
        "desc": "فريش يوميًا",
        "price": 520
      },
      {
        "category": "لحوم كندوز",
        "name": "كبدة كندوز",
        "desc": "بقري فريش يوميًا",
        "price": 520
      }
    ]
  },
  {
    "category": "لحوم ضاني",
    "items": [
      {
        "category": "لحوم ضاني",
        "name": "فخدة ضانى",
        "desc": "",
        "price": 580
      },
      {
        "category": "لحوم ضاني",
        "name": "زند ضانى",
        "desc": "",
        "price": 580
      },
      {
        "category": "لحوم ضاني",
        "name": "رقبة ضانى",
        "desc": "",
        "price": 580
      },
      {
        "category": "لحوم ضاني",
        "name": "موزة ضانى صافى",
        "desc": "",
        "price": 720
      },
      {
        "category": "لحوم ضاني",
        "name": "ريش ضانى بريمو",
        "desc": "",
        "price": 720
      },
      {
        "category": "لحوم ضاني",
        "name": "كبدة ضانى",
        "desc": "",
        "price": 500
      },
      {
        "category": "لحوم ضاني",
        "name": "نيفا ضانى",
        "desc": "",
        "price": 475
      },
      {
        "category": "لحوم ضاني",
        "name": "طرب ضانى",
        "desc": "",
        "price": 420
      },
      {
        "category": "لحوم ضاني",
        "name": "ليه ضانى",
        "desc": "",
        "price": 420
      },
      {
        "category": "لحوم ضاني",
        "name": "كيلو اللحم الضاني",
        "desc": "ريش - رقبة - بيت كلوة",
        "price": 520
      },
      {
        "category": "لحوم ضاني",
        "name": "كيلو كبدة ضاني",
        "desc": "حسب وزن الكبدة كاملة",
        "price": 520
      }
    ]
  },
  {
    "category": "مصنعات",
    "items": [
      {
        "category": "مصنعات",
        "name": "سجق",
        "desc": "",
        "price": 400
      },
      {
        "category": "مصنعات",
        "name": "برجر",
        "desc": "",
        "price": 400
      },
      {
        "category": "مصنعات",
        "name": "كفتة شوى",
        "desc": "",
        "price": 400
      },
      {
        "category": "مصنعات",
        "name": "كفتة داؤود",
        "desc": "",
        "price": 400
      },
      {
        "category": "مصنعات",
        "name": "كفتة صنية",
        "desc": "",
        "price": 400
      },
      {
        "category": "مصنعات",
        "name": "مفروم حواوشى",
        "desc": "",
        "price": 400
      },
      {
        "category": "مصنعات",
        "name": "كفتة أرز",
        "desc": "",
        "price": 400
      },
      {
        "category": "مصنعات",
        "name": "كفتة طرب",
        "desc": "",
        "price": 450
      },
      {
        "category": "مصنعات",
        "name": "رول الربيع",
        "desc": "",
        "price": 450
      },
      {
        "category": "مصنعات",
        "name": "ورق عنب",
        "desc": "",
        "price": 250
      },
      {
        "category": "مصنعات",
        "name": "سمبوسة (١٠ قطع)",
        "desc": "",
        "price": 220
      },
      {
        "category": "مصنعات",
        "name": "كبيبة",
        "desc": "",
        "price": 400
      },
      {
        "category": "مصنعات",
        "name": "ممبار محشى",
        "desc": "",
        "price": 440
      },
      {
        "category": "مصنعات",
        "name": "1/2 كيلو برجر",
        "desc": "بلدي فريش مع تتبيلة الربيع المميزة",
        "price": 175
      },
      {
        "category": "مصنعات",
        "name": "1/2 كيلو سجق",
        "desc": "بلدي فريش مع تتبيلة الربيع المميزة",
        "price": 175
      },
      {
        "category": "مصنعات",
        "name": "1/2 كيلو كفته",
        "desc": "بلدي فريش مع تتبيلة الربيع المميزة",
        "price": 175
      }
    ]
  },
  {
    "category": "حلويات العجل",
    "items": [
      {
        "category": "حلويات العجل",
        "name": "كوارع",
        "desc": "",
        "price": 450
      },
      {
        "category": "حلويات العجل",
        "name": "عكاوى",
        "desc": "",
        "price": 500
      },
      {
        "category": "حلويات العجل",
        "name": "مخ",
        "desc": "",
        "price": 350
      },
      {
        "category": "حلويات العجل",
        "name": "لسان",
        "desc": "",
        "price": 350
      },
      {
        "category": "حلويات العجل",
        "name": "لحمة راس",
        "desc": "",
        "price": 250
      },
      {
        "category": "حلويات العجل",
        "name": "فشة",
        "desc": "",
        "price": 250
      },
      {
        "category": "حلويات العجل",
        "name": "طحال",
        "desc": "",
        "price": 250
      },
      {
        "category": "حلويات العجل",
        "name": "كرشة",
        "desc": "",
        "price": 170
      },
      {
        "category": "حلويات العجل",
        "name": "مخاصى",
        "desc": "",
        "price": 450
      },
      {
        "category": "حلويات العجل",
        "name": "ممبار",
        "desc": "",
        "price": 250
      }
    ]
  }
];
